[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-langserver"]
roots = ["go.mod"]
comment-token="//"
[language-server.golangci-lint-langserver]
command = "golangci-lint-langserver"

[language-server.golangci-lint-langserver.config]
command = [
  "golangci-lint",
  "run",
  "--output.json.path",
  "stdout",
  "--show-stats=false",
  "--issues-exit-code=1",
]


[[language]]
name = "python"
auto-format = true
language-servers = [ "pylsp", "ruff" ]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
[language-server.ruff]
command = "ruff"
args = ["server"]
[language-server.pylsp.config.pylsp]
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true
